### ISSUE TITLE
[Ofo] Fetching the token

### ISSUE THREAD

**Issue by kael** [ubahnverleih/WoBike#10]
According to these [python scripts](https://web.archive.org/web/https://www.cnblogs.com/mengyu/p/7700980.html), there's a way to retrieve the Ofo token.

```python
def get_token(tel, code):
    """
    获取登录时返回的token
    :param tel: 手机号
    :param code: 短信验证码
    :return: token
    """
    url = 'http://san.ofo.so/ofo/Api/login'  # 获取token地址
    headers = {'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, '
                             'like Gecko) Mobile/14E304 MicroMessenger/6.5.7 NetType/WIFI Language/zh_CN'}
    parameter = {"tel": tel, "code": code}
    token = requests.post(url, headers=headers, data=parameter, verify=False).text
    return json.loads(token)["values"]["token"]
```

I've installed the app, registered to the service, removed the app, reinstalled it, and then entered into the login process again. Once I've received the SMS, I've tried unsuccessfully several combinations of types of the following request

```
curl -H "Content-Type: application/json" \
  -X POST -d '{"tel": "+336xxxxxxxx", "code":xxxx"' \
  http://san.ofo.so/ofo/Api/login
```
or 

```
curl -H "Content-Type: application/json" \
  -X POST -d '{"tel": "336xxxxxxxx", "code:xxxx' \
  http://san.ofo.so/ofo/Api/login
```

```
{"errorCode":20001,"msg":"手机号不合法","values":{}}
## 手机号不合法: "Phone number is not valid" (according to Google Translate)
```

Would someone have better luck ?

Grepping the code, not sure that method is still valid, or if it applies to login from other countries than China, though.

I still haven't found a way to get an Ofo token, I'd rather avoid using Mitmproxy (not sure how complicated it is to setup).

**Comment by PierrickP** [comment]
My solution is based on an old apk (1.4 something, before christmas), with mitm. The new version looks totaly differents, i'm not event sure of the right endpoint .. :\

## Get the sms code

```bash
curl --request POST \
  --url https://one.ofo.com/verifyCode_v2 \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'tel=[PHONE]&type=1&ccc=[COUNTRY_CODE]&lng=2.37&lat=48.85'
```
`[PHONE]`: for french number, 9 number (for 06 12 34 56 78 -> `612345678`)
`[COUNTRY_CODE]`: For France: `33`
other params looks mandatory but you can put what you want. I didn't check if there are a check between lat/lng and country_code

## Login with sms code

```bash
curl --request POST \
  --url https://one.ofo.com/api/login_v2 \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'tel=[PHONE]&ccc=[COUNTRY_CODE]&lng=2.37&lat=48.85&code=[SMS_CODE]'
```

@ubahnverleih i ll send you a PR with a clean version of this

**Comment by PierrickP** [comment]
@kael i made some mistake on this PR, fixed by #12

**Comment by ooii** [comment]
Hi,

Thanks for this, it helps a lot.
The problem is that a previous token, provided through the official app, is invalidated if you request a new app. Which means that one phone number cannot be used for both official app and something else.
Any workaround?

**Comment by ubahnverleih** [comment]
So it is also not possible to use the official app on two devices with the same account?

**Comment by dschep** [comment]
i've runinto the device limit issue too. I used mitmproxy to get a token and used it in an app and it worked, then i deployed a second copy of it and that deployment gets errors about 'token in use on another device'

**Comment by ubahnverleih** [comment]
I guess ofo has a wechat integration. The idea would be, to use the API of the WeChat integration. I think the mobike API is also the API for WeChat. But for this we would need a chinese WeChat account i guess. (i don't get any wechat apps with my german wechat account)

**Comment by ubahnverleih** [comment]
Or is ofo integrated into Didi Chuxing?

**Comment by ooii** [comment]
> So it is also not possible to use the official app on two devices with the same account?

Did not test.

**Comment by kael** [comment]
I confirm it's not possible to use the Ofo app and in the meantime the token associated with the phone number used by the app. I use 2 different phone numbers, one for my Ofo data crawler, one for day-to-day use (although Ofo bikes are quite small lol).

**Comment by PierrickP** [comment]
I have wechat, but ofo doesn't propose me wechat ... (just facebook)
For multicycles, i used another phone number 😄 (vive Free 2€/m)

**Comment by PierrickP** [comment]
it's possible to use the same auth token on 2 devices, but if you reauth Ofo ll invalidate your previous token.

**Comment by dschep** [comment]
hah @PierrickP I was thinking of using trello to register a 2nd account for [dc-bike-finder](https://github.com/dschep/dc-bike-finder). Or maybe google voice if that still exists and i can make an account (These are of course US options since that's where I am)

**Comment by ubahnverleih** [comment]
Oh, Ofo and bluegogo are now available via Didi App. Maybe this could be another way.

**Comment by bodiam** [comment]
Hi @PierrickP , you're not running into issues that they rate limit your account? I could imagine if they receive too many request from one account, they'd block it...

**Comment by PierrickP** [comment]
@bodiam not yet 🤞 😄
