### ISSUE TITLE
Bird server 504 error

### ISSUE THREAD

**Issue by luyuliu** [ubahnverleih/WoBike#107]
Seems like Bird is closing their open data entry, again. I wonder if this is a temporary server update or not.

**Comment by luyuliu** [comment]
FYI, https://api.bird.co/user/login. Normally you should be able to get a 404 error if you open that link in a browser.

**Comment by HoneyBass** [comment]
try at https://api.birdapp.com/ there you can get the birds

**Comment by kaets** [comment]
now both api.bird.co and api.birdapp.com are giving 403 forbidden errors when following the tutorial (i.e. sending a post request to /user/login with Device-id and Platform headers and email body). 2 days ago, api.birdapp.com was working with the exact same script.

**Comment by robbi5** [comment]
Fixed in 20da8cf2d91fceaf4700e43d6876606172dffe1c - works again
