### ISSUE TITLE
JUMP revamp

### ISSUE THREAD

**Issue by kaets** [ubahnverleih/WoBike#112]
Now that JUMP is owned by Uber, it seems that the JUMP Scooter/Bike API is now run through the Uber API rather than the old JUMP API.

I used Charles and Genymotion to try and figure out what API calls are being made, but since Uber isn't supported on Genymotion (I think its due to an architecture mismatch - Genymotion has a different architecture than that supported by the newest Uber app), I was unable to find out the API calls.

I'm guessing API calls for viewing JUMP scooters are sent to cn.uber.com, as this is the API endpoint for Uber taxi service.

Either way, it would be awesome to revamp the JUMP API section and look into the Uber scooter API, especially given how prevalent JUMP scooters and bikes are, at least in Austin, TX.

**Comment by yoshimo** [comment]
Closed by https://github.com/ubahnverleih/WoBike/pull/157 isn't it?

**Comment by kaets** [comment]
Yeah, nice job! :)
