### ISSUE TITLE
Bird POST Request

### ISSUE THREAD

**Issue by himanshu20792** [ubahnverleih/WoBike#119]
Not receiving the token when using POST

`import requests
 URL = "https://api.birdapp.com/user/login"
email = {"email": 'XXXX@gmail.com'}
r = requests.post(URL, data= email)
text = r.text
print(text)
`
Error: HTTP 415: Unsupported Media type

**Comment by rrozek** [comment]
hi, you need a few additional headers for Bird as described in 
https://github.com/ubahnverleih/WoBike/blob/master/Bird.md
User-Agent: Bird/4.41.0 (co.bird.Ride; build:37; iOS 12.3.1) Alamofire/4.41.0
Device-Id: <GUID>
Platform: ios
App-Version: 4.41.0
Content-Type: application/json

also mind single `'` in your email provided. should be `"` probably

**Comment by himanshu20792** [comment]
I did, below is the code and error I received
`
headers = {"User-Agent": "Bird/4.41.0 (co.bird.Ride; build:37; iOS 12.3.1) Alamofire/4.41.0",
           "Device-Id": "54253685-49a0-48e0-a239-759e77639506",
           "Platform": "ios",
           "App-Version": "4.41.0",
           "Content-Type": "application/json"}

r = requests.post(URL, data= email, headers = headers)
`

Error: {"code":400,"message":"Unable to process JSON","details":"Unrecognized token 'email': was expecting ('true', 'false' or 'null')"}

**Comment by himanshu20792** [comment]
Its resolved. 

You have to use json= keyword argument instead of data= in the Post request above.
