### ISSUE TITLE
API support for scooter chargers (Bird, and Lime)

### ISSUE THREAD

**Issue by lbeougher** [ubahnverleih/WoBike#120]
I was wondering if anyone has come across public endpoints for user roles of 'chargers' for the Bird and Lime services. For example, being able to find scooters ready for capture for charging, and available dropoff locations. Any direction is much appreciated. Thanks.

**Comment by robbi5** [comment]
see https://github.com/ubahnverleih/WoBike/issues/58 - the problem of no contributors with active charger accounts still exists :)
