### ISSUE TITLE
Jump bike endpoints deprecated?

### ISSUE THREAD

**Issue by finncodes** [ubahnverleih/WoBike#131]
Hello,

I just tried getting both the system information and the free bike status from the endpoints on both the DC and SF Jump bike API hosts and I got 404 errors - I believe the service could be getting shut down as neither have responded with any available bikes for a while now.

**Comment by dschep** [comment]
Don't have time to make a pr.. but here are the new urls:

bike URL:
* dc - https://gbfs.uber.com/v1/dcb/free_bike_status.json
* sf - https://gbfs.uber.com/v1/sfb/free_bike_status.json

scooter URLs:
* dc - https://gbfs.uber.com/v1/dcs/free_bike_status.json
* sf - https://gbfs.uber.com/v1/sfs/free_bike_status.json

**Comment by kaets** [comment]
also some for austin, found quite by accident!
https://gbfs.uber.com/v1/atxb/free_bike_status.json
https://gbfs.uber.com/v1/atxs/free_bike_status.json

**Comment by davidwim** [comment]
JUMP Vehicles can now be found under the Lime API
