### ISSUE TITLE
Pony Bikes

### ISSUE THREAD

**Issue by yoshimo** [ubahnverleih/WoBike#138]
While the Pony App is very light on trackers compared to others (only  Crashlytics and Firebase), its communication is a bit nasty to read.

To get data it goes to

> pony-bikes-f8cf9.firebaseio.com
via websocket

It additionally queries
https://api.getapony.com/georegion/resolve?latitude=<X>&longitude=<Y>

If you are outside of the pony bike area you get:

`{"status":"UNRESOLVED"}`

If you query Oxford for example with
```
                    "latitude": 51.75632,
                    "longitude": -1.25993,
```
You will receive the proper area tag:

`{"region":"Oxford","status":"SUCCESS"}`

**Comment by yoshimo** [comment]
[1_raw.hcy.txt](https://github.com/ubahnverleih/WoBike/files/4022015/1_raw.hcy.txt)
[2_raw.hcy.txt](https://github.com/ubahnverleih/WoBike/files/4022016/2_raw.hcy.txt)
[3_raw.hcy.txt](https://github.com/ubahnverleih/WoBike/files/4022017/3_raw.hcy.txt)

The replies from the rest api over websocket about available scooters and bikes are minified so it takes additional effort to match the letters to their meaning later on
[ws_4.wscy.txt](https://github.com/ubahnverleih/WoBike/files/4022018/ws_4.wscy.txt)

**Comment by njoylab** [comment]
Hello yoshimo, usually firebase datastore serves the results also without websockets.
In this case you can get the list directly from
https://pony-bikes-f8cf9.firebaseio.com/rest/bicycles.json
https://pony-bikes-f8cf9.firebaseio.com/rest/scooters.json

**Comment by yoshimo** [comment]
how did you find these?

**Comment by njoylab** [comment]
It's in your "ws_4.wscy.txt" response
It has the path of the objects. From there you can see the name of the entities and the path.
You need just to add .json and use the base url of the project
`pony-bikes-f8cf9.firebaseio.com
`

**Comment by yoshimo** [comment]
@njoylab  is that something one can adapt to #81 too? That wire traffic does't explicitly mention rest

**Comment by njoylab** [comment]
Sorry for the delay. I think it could be the same, but unfortunately I'm not able to find the name of the table/model

**Comment by Ifmon** [comment]
consider closing the issue?
https://github.com/ubahnverleih/WoBike/pull/265
