### ISSUE TITLE
Mobike URL Connection Error

### ISSUE THREAD

**Issue by umi85** [ubahnverleih/WoBike#142]
Dear All,

I gues mobike has changed the API. The URL http://app.mobike.com/api/nearby/v4/nearbyBikeInfo throws an connection error.

I found this online documentation by this seems to be only for the chinese market.
http://docs.mobike.com/en/international/nearbyBikeInfo.html
http://docs.mobike.com/cn/

Best

Florian

**Comment by yoshimo** [comment]
Host: global-n-mobike-g.mobike.com
POST /api/nearby/v4/nearbyBikeInfo

**Comment by umi85** [comment]
Thanks. Works perfect for me.

How do you know? Is there a way to reverse engineer the code of an app. Do you have an hint for me? A tutorial, video or a tool? I would love to add some other provider.

Best Florian

**Comment by yoshimo** [comment]
Well usually you don't have to go that far and decompile and disassemble the apk file.
Most of it can be done with a Proxy like Charles Proxy or BurpSuite or something local as described in
https://github.com/ubahnverleih/WoBike/issues/58#issuecomment-570796716 @umi85 .Run the app and watch them ask their endpoints and get a json file back (or whatever else they might use)
