### ISSUE TITLE
BirdAPI ´Bird Response: {"code":401,"message":"Invalid authorization header format."}

### ISSUE THREAD

**Issue by kireznieh** [ubahnverleih/WoBike#153]
I've got the following issue. 
I get a token sent to my email but I couldn't figure out how to pass the auth header correctly to get a  response.

My code looks the following:
`var BirdRestClient = new RestClient("https://api.birdapp.com/bird/nearby?latitude=37.77184&longitude=-122.40910&radius=1000");
                var scooterRequest = new RestRequest(Method.GET);
                scooterRequest.AddHeader("Authorization", "Bird"+BirdTokenCanvasText.text.Trim(' '));
                scooterRequest.AddHeader("Device-id", "123E4567-E89B-14D3-B456-426655440100");
                scooterRequest.AddHeader("App-Version", "4.41.0");
                scooterRequest.AddHeader("Location", " {\"latitude\":37.77249,\"longitude\":-122.40910,\"altitude\":500,\"accuracy\":100,\"speed\":-1,\"heading\":-1}");
            IRestResponse birdresponse = BirdRestClient.Execute(scooterRequest);`

I already tested it with directly inserting the token as a plain string but it also didn't work out.

**Comment by salanza** [comment]
Can you provide a bit more information? For example, What library are you using to instantiate that RestClient object? The syntax looks a bit like JavaScript but I do not recognize _RestClient_

**Comment by kireznieh** [comment]
I am using C# and the following Nuget RestClient package.
https://www.nuget.org/packages/RestSharp.
Querying other API's like the Tier or Hive API's work decent.

**Comment by salanza** [comment]
For the token in the Auth header, did you leave a space between the word "Bird" and the actual token? [https://github.com/ubahnverleih/WoBike/blob/master/Bird.md](This Doc) includes a space in all mentions of the auth header.

**Comment by kireznieh** [comment]
Not working even if I add a space inbetween the keyword Bird and the token :-(.

**Comment by salanza** [comment]
Is it the same 401 error? Or are you getting an empty response?

**Comment by kireznieh** [comment]
Same Issue if I try it via Postman. See the attached screenshot
![birdviaPostman](https://user-images.githubusercontent.com/35397707/76553146-56a7db00-6494-11ea-9c4e-eb30aa65963e.png)

**Comment by kireznieh** [comment]
My Request via Postman is working and I found out that I handed over the whole access + refresh string which caused my previous issue.
But now I am experiencing a parsing issue. See the Screenshot below
![grafik](https://user-images.githubusercontent.com/35397707/76556772-7a6e1f80-649a-11ea-97ee-27537b855f8e.png)

**Comment by kireznieh** [comment]
Oh and my Code looks like this now
![grafik](https://user-images.githubusercontent.com/35397707/76556865-a7bacd80-649a-11ea-8770-b7efe00e3bbb.png)
