### ISSUE TITLE
Refresh-Token for Bird

### ISSUE THREAD

**Issue by HoneyBass** [ubahnverleih/WoBike#159]
Do you guys know how to get a new token from the Bird API. Mine is expired and i don't wanna authentificate my mail for every new token. The magic link sends you an access token and a refresh token. What do you guys do with the refresh Token and is it maybe a key to get a new access token.

**Comment by kireznieh** [comment]
Same thing here I need to check my email every time I query the api. 
But I really don't know how to use the refresh token.
Would be great if anybody could figure that out!

**Comment by tomerbal** [comment]
+1

**Comment by watzon** [comment]
Send a POST request to `api-auth.birdapp.com/api/v1.refresh/token` with the **Authorization** header `Bearer [refresh token]`. You'll get a new access token and refresh token in return.
