### ISSUE TITLE
[gobee.bike] unavailable endpoint

### ISSUE THREAD

**Issue by PierrickP** [ubahnverleih/WoBike#16]
`http://aws.gobee.bike` is not the application's endpoint and sometime it's down (like now -_- )

It's probably for partners or data analysis but not used on the mobile application.
We should try to get a more reliable endpoint

Edit: it's back

**Comment by PierrickP** [comment]
Down since yesterday (25th jan)

**Comment by kael** [comment]
I tried to decompile the APK using this [online APK decompiler](http://www.javadecompilers.com/apk) but it fails, perhaps because of encoding.

Have you been able to get the .dex file ?

**Comment by PierrickP** [comment]
Their android app is made with kotlin and classic tools (dex2jar, apktool) look to be not totally compatible.
You can open with JD-gui https://ufile.io/5bwjm

**Comment by PierrickP** [comment]
Oh i finaly found 2 endpoints: 
`https://appaws.gobee.bike/` & `https://api.gobee.bike/`

**Comment by kael** [comment]
Awesome
