### ISSUE TITLE
Tier Api change

### ISSUE THREAD

**Issue by tilchl** [ubahnverleih/WoBike#160]
Tier seems to have changed thei api routing.
While ````https://platform.tier-services.io/```` still exists the routes ``vehicle`` and ``zone`` are responding 
```401```

**Comment by JKamue** [comment]
I updated the documentation in pull request #167 according to this API documentation: https://www.notion.so/TIER-API-Version-1-0a9bfc571e8f41859d994e736a51315b

**Comment by tilchl** [comment]
thanks.
