### ISSUE TITLE
[Ofo] API python implementation

### ISSUE THREAD

**Issue by qxzzxq** [ubahnverleih/WoBike#17]
Hi all, thanks a lot for all of you for the great project ! I am currently looking for bike sharing APIs and your documentation really helps me a lot.

I just created a python package for interfacing with the ofo API :) 
https://github.com/qxzzxq/pyofo

**Comment by dschep** [comment]
Awesome! I'm definitely gonna use this 👍

**Comment by PierrickP** [comment]
Nice, you can add on https://github.com/ubahnverleih/WoBike/blob/master/Ofo.md#implementations

**Comment by qxzzxq** [comment]
I created a pull request 😄 

#18

**Comment by PierrickP** [comment]
:+1:
