### ISSUE TITLE
Lime 401 Unauthorized

### ISSUE THREAD

**Issue by davidwim** [ubahnverleih/WoBike#171]
I'm trying to get the OTP request for the Lime API and this is the error that I'm getting: ***Error 401*, Similar to 403 Forbidden, but specifically for use when authentication is possible but has failed or not yet been provided. The response must include a WWW-Authenticate header field containing a challenge applicable to the requested resource.** I'm certain that I've done it correctly. I'm using this URL: `https://web-production.lime.bike/api/rider/v1/login?phone=%+1XXXXXXXXXX`

Does the API now require certain headers to get an OTP Code?

**Comment by mxdr** [comment]
The phone param needs to start with `%2B`
For example, `%2B46701234567` is the format for `+46 70 123 4567`

**Comment by davidwim** [comment]
Thanks for the reply. I knew about this a few days after making this Issue by running a proxy when using Logging-In to Lime.
