### ISSUE TITLE
Lime email login

### ISSUE THREAD

**Issue by Timo1603** [ubahnverleih/WoBike#182]
Hi everyone,

first I tried to login with my phone.
I did the same like the README said:
`GET https://web-production.lime.bike/api/rider/v1/login?phone=%2B...`
But the answer was 401 Unauthorized.

Now I want to login with my email and I tried the following request:
`GET https://web-production.lime.bike/api/rider/v1/login?email=...`
But I also get 401 😞 

Can anyone help me?

**Comment by davidwim** [comment]
Did you have all of the parameters and headers included in your request? Also make sure to include the country code after the %2B ?￼

**Comment by Timo1603** [comment]
I don't know why but I tried my request again without any changes and now it works...
Anyhow thanks for reply :)
