### ISSUE TITLE
Add Sigo

### ISSUE THREAD

**Issue by robbi5** [ubahnverleih/WoBike#184]
Site: https://sigo.green
iOS: https://apps.apple.com/de/app/sigo-sharing/id1492307478
Android: https://play.google.com/store/apps/details?id=com.sigo.app

Using Fleetbird:
https://sigo.frontend.fleetbird.eu/api/prod/v1.06/
https://sigo.frontend.fleetbird.eu/api/prod/v1.06/locations/
https://sigo.frontend.fleetbird.eu/api/prod/v1.06/cars/
https://sigo.frontend.fleetbird.eu/api/prod/v1.06/map/cars/

**Comment by davidwim** [comment]
I'll get it documented sometime this week.

**Comment by davidwim** [comment]
[Done](https://github.com/ubahnverleih/WoBike/blob/master/Sigo.md), I didn't have much to work off of so it's not very detailed.
