### ISSUE TITLE
Add go sharing

### ISSUE THREAD

**Issue by robbi5** [ubahnverleih/WoBike#189]
Site: https://go-sharing.nl
iOS: https://apps.apple.com/us/app/go-sharing/id1477465763?ls=1
Android: https://play.google.com/store/apps/details?id=nl.gosharing.gourban.app

Looks like a white label version of https://gourban.co/platform.html

Base URL: https://greenmo.core.gourban-mobility.com/front

https://greenmo.core.gourban-mobility.com/front/settings?keys=minimumRequiredAppVersion,support.methods,navigation,payment.methods,areas,booking,user.feedback,reservation.extension,user.accounts,errorhandling,user.requiredFields,logins,plugins.auth.google,app.main,screens.login,packages,theme,theme.splashScreen,theme.colors.main,theme.colors.main.dark,theme.colors.map,theme.colors.map.dark,map,map.clusterImage,rental,plugins.onesignal,plugins.activated,vehicles,tutorial,currency,qr.code,rewardStations,radar,additions.insurance

https://greenmo.core.gourban-mobility.com/front/vehicles?lat=51.92489467429188&lng=4.46729341260345&rad=1000

**Comment by davidwim** [comment]
If you've got the endpoints, why don't you document it?

**Comment by davidwim** [comment]
There wasn't much to work with, but I've documented it.
