### ISSUE TITLE
Add Felyx

### ISSUE THREAD

**Issue by dennisdebel** [ubahnverleih/WoBike#190]
# Felyx

[felyx](https://felyx.com/) is a moped-sharing company based in Europe. It's platform is based on fleetbird...so:

There is *no* authentication or special headers and only `GET`-Requests required for the API-Endpoint `https://felyx.frontend.fleetbird.eu/api/prod/v1.06/`. You can request all(?) vehicles with `https://felyx.frontend.fleetbird.eu/api/prod/v1.06/map/cars/` or filter them by bbox like `https://felyx.frontend.fleetbird.eu/api/prod/v1.06/map/cars/?lat1=46.8339&lat2=55.829&lon1=4.205&lon2=27.653` or show the 20 nearest vehicles around a location with `https://felyx.frontend.fleetbird.eu/api/prod/v1.06/cars/?lat=53.4374&lon=9.9955`.

Polygons with regions and parking restrictions are available on `https://felyx.frontend.fleetbird.eu/api/prod/v1.06/territories/all/` (`type: 0` looks like free floating region and `type: 1` are no parking zones).

Vehicle types with images are available on `https://felyx.frontend.fleetbird.eu/api/prod/v1.06/cars/types/`

**Comment by davidwim** [comment]
Created

**Comment by b-a0** [comment]
@W1MMER the [current links](https://github.com/ubahnverleih/WoBike/blob/master/Felyx.md) seem to have gone down. Can this issue be re-opened?

android: https://play.google.com/store/apps/details?id=com.felyx.android
ios: https://apps.apple.com/us/app/felyx/id1250107307

**Comment by b-a0** [comment]
My bad, it was probably a network problem on their end, the links work again. Please disregard my earlier request.

**Comment by b-a0** [comment]
@W1MMER the links of this provider still work, but seem to return only a tiny subset of the data. My hunch is that either:
- They migrated to almost all of the vehicles to another platform or API URL
- There is some paging parameter that needs to be passed to the URL
