### ISSUE TITLE
Bird scooters returned in a strange way

### ISSUE THREAD

**Issue by mperezmartinezdev** [ubahnverleih/WoBike#192]
When I did a request to get all the close scooters from a specific point all the returned values display a line on the map and doesn't matter where the point it is. If I change the radius paramether it only expand or reduce that line.

Example:
This is the query from postman : 
https://api.birdapp.com/bird/nearby?latitude=40.4380638&longitude=-3.7495758&radius=1000
Authorization: Bird {mytoken here }
Device-id: 123E4567-E89B-12D3-A456-426655440000
App-Version: 4.41.0
Location: {"latitude":41.65172,"longitude":-0.88423,"altitude":500,"accuracy":100,"speed":-1,"heading":-1}

And if I insert the response into a map it display like this:
https://gyazo.com/c32a4fa5aa809b98f596ae507c314e55

I don't know what happend but i so stuck with this. 
Has anyone similar issue or know how to solve it? Any help would be great.

**Comment by davidwim** [comment]
That's not the first time I've seen this. There's one of those all in one scooter maps named Corkey that used to do this as well. I contacted the developer at this address: netcorkey@gmail.com and he managed to fix the bug straight away. You may want to contact him and see how he patched it.

**Comment by mperezmartinezdev** [comment]
@davidwim Thanks for the help. I'm going to send an email to them and lets see if they tell me how they fixed it

**Comment by davidwim** [comment]
Did you manage to get the issue fixed?

**Comment by mperezmartinezdev** [comment]
@davidwim  Not yet. They didn't answer my email.

**Comment by ricffb** [comment]
Hi,
I managed to fix it. I included a pull request #195 . 
The gist: you need to include a user-agent with the get request:
Bird/4.119.0 (co.bird.Ride; build:3; iOS 14.3.0) Alamofire/5.2.2
