### ISSUE TITLE
Problem with BIRD api.

### ISSUE THREAD

**Issue by benferpo** [ubahnverleih/WoBike#193]
HI all, 

I'm trying accessing Bird API using python.

I got my token using POST to https://api-auth.prod.birdapp.com/api/v1/auth/email, but we try doing new POST to https://api-auth.prod.birdapp.com/api/v1/auth/magic-link/use in order to get LONG STRING for accessing, i get a request like this:

{"code":400,"message":"The magic link you used is no longer valid."}  Any idea?

The code of python is:

token_str = {"token":"w1EcoJjYRgKne5I9B04zElQ"}
url_token = "https://api-auth.prod.birdapp.com/api/v1/auth/magic-link/use"
  
headers_2 = {"User-Agent": "Bird/4.53.0 (co.bird.Ride; build:24; iOS 12.4.1) Alamofire/4.53.0"
,"Platform": "ios",
"App-Version": "4.53.0",
"Content-Type": "application/json",
"Device-Id": str(uuid.uuid4())}
 
auth_2 = requests.post(url_token, data=json.dumps(token_str), headers=headers_2 )
   
print (auth_2.text)

Thanks

**Comment by ricffb** [comment]
Hi @benferpo,

The token is only valid for a limited time. Each time you call the login route you get a new token (via mail) that you have to confirm.

Note that you usually only do this once and the just use the `refresh` functionality to refresh your access token.

A hint: use a service like [10 minute mail](https://10minutemail.net/) to have a bunch of throw away addresses at hand.

**Comment by benferpo** [comment]
Thanks @ricffb 

It works now. Yes, I think that it was a problem with validity of token. 

Best.
