### ISSUE TITLE
Need help for Mobike and ofo

### ISSUE THREAD

**Issue by hamutaro89** [ubahnverleih/WoBike#2]
Hi, I've failed to get return value on both Mobile and ofo. Please help.

1. ofo, I have no idea where should I register for the "token"
{
    "errorCode": 10003,
    "msg": "You logged in ofo on another device.",
    "values": {}
}

2. Mobike, I've followed your every steps, including Referer to https://servicewechat.com/ on header. But still error 403.

**Comment by ubahnverleih** [comment]
I guess the only way to get your token is to sniff the request of the App via mitm proxy.

**Comment by hamutaro89** [comment]
ok, will look into that mitm proxy, thanks. Any idea on the Mobike?

**Comment by ubahnverleih** [comment]
For mobike: Try to set header `'user-agent': "MicroMessenger/6.5.4.1000 NetType/WIFI Language/zh_CN"`
Curl worked for me with: `curl  -H 'Referer: https://servicewechat.com/' --data "latitude=22.5376&longitude=114.0577" 'https://mwx.mobike.com/mobike-api/rent/nearbyBikesInfo.do' -H "user-agent: MicroMessenger/6.5.4.1000 NetType/WIFI Language/zh_CN" -v`

**Comment by hamutaro89** [comment]
Thanks, the curl worked for me too. however i cant get it to work on postman with form request, but nvm the curl is good enough for me. Thanks again

**Comment by ubahnverleih** [comment]
I added the user-agent info to readme

**Comment by hidingmode** [comment]
For ofo, I tried to do
```
curl --request POST --url https://one.ofo.com/verifyCode_v2 --header "content-type: application/x-www-form-urlencoded" --data "tel=81234567&ccc=65&type=1&lng=2.37&lat=48.85"
```
but it returns
```
{"errorCode":20009,"msg":"This mobile phone number has not been registered. Do you want to sign up now?","values":{}}
```

**Comment by dschep** [comment]
@hidingmode did you install the ofo app on your phone and open account with that phone number? If not, that error is expected.
