### ISSUE TITLE
Add Nureon

### ISSUE THREAD

**Issue by henrus1** [ubahnverleih/WoBike#203]
I don't have any other details but they're now operating in Australia, New Zealand, the UK and South Korea.

https://www.rideneuron.com

**Comment by aPersonInNZ** [comment]
This will be added. But they unfotuantly use SSL Pinning in their app. I have been able to get their endpoints before though.

**Comment by robbi5** [comment]
iOS: https://apps.apple.com/SG/app/id1240649186?mt=8
Android: https://play.google.com/store/apps/details?id=com.hhyu.neuron

Base URL: https://au-api.neuron-mobility.com
Using also firebase: https://neuronpublic-cdb04.firebaseio.com (but not sure for what)

The API uses a custom `sign` signature header. This is built by using the GET/POST parameters, the `timestamp` header and a secret.

```python
import hashlib
import urllib.parse
from collections import OrderedDict

# get params or post body
params = {"distance":"335","latitude":"-27.469746172603777","longitude":"153.02297267664835"}
# add timestamp from header
params["timestamp"] = "1616942614041"

secret = "neuron(!@#2018^&*)mobility"

params = OrderedDict(sorted(params.items()))
url_params = urllib.parse.urlencode(params, doseq=True, quote_via=lambda x, *_: x)
hash_input = url_params + "#" + secret
digest = hashlib.md5(hash_input.encode())
print(digest.hexdigest())
```

To get the auth header (jwt), you have to login. First you have to aquire an password / login code that is sent to you by sms:
```
POST https://au-api.neuron-mobility.com/api/auth/sms

timestamp: 1616944256428
sign: 6cb9133f9d760f10d87541f060210aef

{"countryCode":"61","mobile":"401061840"}
```

After that, you can get the jwt auth header:
```
POST https://au-api.neuron-mobility.com/api/auth/v1/login

timestamp: 1616944354546
sign: 4133bccf633a388c127484da67e8692d

{"password": "763618","username": "401061840"}

{
	"data": {
		"token": "<jwt>",
		"refreshToken": "<token>",
		"isNewUser": true,
		"emailMarketing": true,
		"notificationMarketing": true,
		"locationMarketing": true,
		"usageTracking": true,
		"smsMarketing": true
	}
}
```

To get positions, put the jwt into the `X-Authorization` header:
```
GET https://au-api.neuron-mobility.com/api/scooters/userMap?distance=335&latitude=-27.469746172603777&longitude=153.02297267664835

X-Authorization: Bearer <jwt>
timestamp: 1616942614041
sign: 261492ea9bbf5bafca7ddc6dbba86c5d

{
	"data": [{
		"id": 5372,
		"qrCode": "51207883",
		"vehicleType": "SCOOTER",
		"helmetLock": true,
		"status": "IN_STATION",
		"latitude": -27.46785,
		"longitude": 153.02368,
		"remainingBattery": 0.46,
		"generation": "N3",
		"remainingRange": 13
	}, {
		"id": 6004,
		"qrCode": "51250199",
		"vehicleType": "SCOOTER",
		"helmetLock": true,
		"status": "IN_STATION",
		"latitude": -27.46757,
		"longitude": 153.02251,
		"remainingBattery": 0.67,
		"parkingTime": 1616934876000,
		"generation": "N3",
		"remainingRange": 32,
		"photoView": {
			"large": "https://images.neuron.sg/fit-in/800x/AU/SCOOTER/bf77e248d81145c4a548.JPEG",
			"small": "https://images.neuron.sg/fit-in/200x/AU/SCOOTER/bf77e248d81145c4a548.JPEG"
		}
	}
        //...
        ]
}
```

**Comment by aPersonInNZ** [comment]
I've used SSL Kill Switch on a jailbroken iPhone to get those endpoints. But thanks! Is it okay if I copy and paste that into a new file as the documentation?

**Comment by W1MMER** [comment]
As a follow up, thanks @robbi5 for taking the time to reverse the android app and especially for figuring out how their signing mechanism works. Much appreciated

**Comment by nutterthanos** [comment]
> Using also firebase: https://neuronpublic-cdb04.firebaseio.com (but not sure for what)

{
  "error" : "The Firebase database 'neuronpublic-cdb04' has been deactivated."
}
