### ISSUE TITLE
Invalid param

### ISSUE THREAD

**Issue by galcopi** [ubahnverleih/WoBike#22]
Hi I'm trying to integrate ofo following this instructions and the response in the first endpoint (verifyCode_v2) is the following. Any help? :) Thanks!

{
    "errorCode": 40001,
    "msg": "Invalid param",
    "values": {}
}

**Comment by PierrickP** [comment]
Your phone number should be registered before (it's not documented :\ )
Use your phone to create your account, then use the documentation to get the token

:warning: one token per account, if you login by api, you ll be loggued out on your phone.

**Comment by galcopi** [comment]
Thanks @PierrickP !! I'm already registered and I still receive the same response... :/

**Comment by PierrickP** [comment]
@galcopi yes, tried right now with my personal account.
Can you copy/past me your request ? (hide your phone num). What is your country ?

**Comment by galcopi** [comment]
Ouch!

Sure @PierrickP , this is my request:

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://one.ofo.com/verifyCode_v2?tel=6XXXXXXXX&type=1&ccc=34&lng=41.39&lat=-3.46",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_HTTPHEADER => array(
    "cache-control: no-cache",
  ),
));

I've registered with my phone months ago! I already use the service!

Country: Spain.

Thank you sooooooo much 😄

**Comment by PierrickP** [comment]
Missing content-type

try

```PHP
curl_setopt_array($curl, array(
  CURLOPT_URL => "https://one.ofo.com/verifyCode_v2",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "tel=6XXXXXXX&type=1&ccc=33&lng=2.37&lat=48.85",
  CURLOPT_HTTPHEADER => array(
    "content-type: application/x-www-form-urlencoded"
  ),
));
```

**Comment by galcopi** [comment]
Thaaaaaaaaaank youuuu so much @PierrickP !

You were right! It's know working.

Just one more thing:

The response I'm receiving when I try to get /nearbyofoCar is:

{"errorCode":10003,"msg":"You logged in ofo on another device.","values":{}}

Any comment?? 😃

**Comment by PierrickP** [comment]
You probably use an old auth token.
I don't think tokens are IP restricted

**Comment by galcopi** [comment]
Yes... It seems to be a restriction... I tried with a second phone number and I receive the same answer: You logged in ofo on another device.

**Comment by dschep** [comment]
Yup. I registered on my phone. logged out. logged in with it as documented in [Ofo.md](https://github.com/ubahnverleih/WoBike/blob/master/Ofo.md).

**Comment by davidwim** [comment]
Ofo has closed down
