### ISSUE TITLE
Add Avocargo (cargo bikes in Berlin)

### ISSUE THREAD

**Issue by derhuerst** [ubahnverleih/WoBike#224]
Website: https://www.avocargo.one
iOS: https://apps.apple.com/us/app/avocargo/id1570221120
Android: https://play.google.com/store/apps/details?id=com.avocargo.android

Active in
- Berlin Prenzlauer Berg

**Comment by robbi5** [comment]
Just another fleetbird:

https://avocargo.frontend.fleetbird.eu/api/prod/v1.06/
https://avocargo.frontend.fleetbird.eu/api/prod/v1.06/locations/
https://avocargo.frontend.fleetbird.eu/api/prod/v1.06/cars/
https://avocargo.frontend.fleetbird.eu/api/prod/v1.06/map/cars/

**Comment by BastelPichi** [comment]
Can you close this @W1MMER?
