### ISSUE TITLE
Lime API can't login with email

### ISSUE THREAD

**Issue by rainyjonne** [ubahnverleih/WoBike#239]
Hello, I've tried the same way that the document said by using the same params (email, name, password, platform) but I always got a **401 Unauthorized result** in return... so confused 😕 😭 

I've used Windows, Android, and iOS for platform parameters before but it won't work. I'm not a Lime rider yet, so I choose email to log in. I've received a lime cookie but I still can not get a login token 😢 

Do anybody knows why?

![image](https://user-images.githubusercontent.com/40749393/162616721-2f4c928d-32f9-48dd-9883-8c0c58da5db1.png)

![image](https://user-images.githubusercontent.com/40749393/162616744-b82cd28f-84da-4e63-8f13-776a8746f523.png)

**Comment by W1MMER** [comment]
Old versions of the app used passwords instead of magic-links.

**Comment by BastelPichi** [comment]
[lime](Lime.md) has been updated. Please close this.
