### ISSUE TITLE
Israel support for mobike and ofo

### ISSUE THREAD

**Issue by yoavst** [ubahnverleih/WoBike#24]
Ofo and Mobike recently launched a pilot in Israel. 
Mobike api works for me in Israel, I'll check ofo and update later.

**Comment by PierrickP** [comment]
Great news !
I confirm, it's works
![image](https://user-images.githubusercontent.com/1214544/39802179-ad1144fc-536d-11e8-98fd-71cefc5c46d1.png)
(with my project https://github.com/PierrickP/multicycles who use this)

Cities per providers are not really up to date
