### ISSUE TITLE
Ringing Lime Bike, even via POST simply returns 401 Unauthorised.

### ISSUE THREAD

**Issue by iVictory2004** [ubahnverleih/WoBike#246]

**Comment by W1MMER** [comment]
Did you get this problem solved?

**Comment by iVictory2004** [comment]
Nope i did not

**Comment by iVictory2004** [comment]
I didn't but I also didn't get to reuse the thing again since exams, I'll inform you in like a month=))

**Comment by W1MMER** [comment]
So turns out the endpoint that I provided was for the Juicer API. I've just updated the doc now.

**Comment by BastelPichi** [comment]
@W1MMER Can you close this?

**Comment by BastelPichi** [comment]
thx
