### ISSUE TITLE
Bolt Ringing

### ISSUE THREAD

**Issue by mlodyskiny** [ubahnverleih/WoBike#247]
Is there an API that can let me ring a Bolt scooter?

**Comment by BastelPichi** [comment]
https://github.com/ubahnverleih/WoBike/blob/master/Bolt.md#ring-scooter

**Comment by BastelPichi** [comment]
Can we close this?

**Comment by 0ez** [comment]
yeah like why not

**Comment by BastelPichi** [comment]
> yeah like why not

Then do it, I cant lol

**Comment by BastelPichi** [comment]
Bruh close this... xD

**Comment by roledxd** [comment]
Haha

**Comment by BastelPichi** [comment]
> Haha

I am totally not raging right now xD

**Comment by BastelPichi** [comment]
@robbi5 Thanks...

**Comment by mlodyskiny** [comment]
It's troll or get trolled.
