### ISSUE TITLE
[Not an Issue] Redoing and universal py lib

### ISSUE THREAD

**Issue by BastelPichi** [ubahnverleih/WoBike#251]
Hello,

I've discovered this project and it's awesome. As I'm myself using this for some projects, I've started creating a universal python library. It currently only has a implementation for Bolt in it, but I'm working on other providers. The implementation has nearly everything in it, from creating an account to renting scooters. I'm not yet done with the docs, but it will still be a help, if you're trying to implement bolt.

Apart from this, I'm thinking of redoing most of the documents here, so be prepared ;)

Repository: [https://github.com/BastelPichi/pyscooter](https://github.com/BastelPichi/pyscooter)
Bolt Integration: [https://github.com/BastelPichi/pyscooter/blob/main/providers/bolt.py](https://github.com/BastelPichi/pyscooter/blob/main/providers/bolt.py)

Docs: [https://pyscooter.readthedocs.io/en/latest/](https://pyscooter.readthedocs.io)

Best regards

**Comment by ubahnverleih** [comment]
Feel free to add a link on the Bolt file. Maybe add some section for software implementing the service

**Comment by BastelPichi** [comment]
For the docs, as said, I'm still working on that.

Added a dierct link to the bolt file.

Also made my first update to the Bolt.md file. (#252 )
