### ISSUE TITLE
Dead link in Tier.md

### ISSUE THREAD

**Issue by dasslefl** [ubahnverleih/WoBike#272]
Both https://www.notion.so links in [Tier.md](https://github.com/ubahnverleih/WoBike/blob/master/Tier.md) are dead.

**Comment by BastelPichi** [comment]
See #273.
Can you merge outstanding commits @ubahnverleih ?

**Comment by robbi5** [comment]
thanks for the notice, closed in de9995b611fe12e5604aeffdceda15794ece32ba
