### ISSUE TITLE
Bird POST Token

### ISSUE THREAD

**Issue by black-tea** [ubahnverleih/WoBike#33]
Using the instructions provided, the response to my POST request at the Bird API didn't include a JWT in the response. As mentioned in #32 there is just a value of an expiration date, such as below:

`{'id': 'd9b7a40f-59f6-4c94-ae47-e13a5d5d8b74', 'expires_at': '2018-06-23T18:34:51.331Z'}`

Is the token provided somewhere else and I am just missing it?

**Comment by ubahnverleih** [comment]
I got the token only on the first request with a id and mail address, after that only expire date. Can you try if you get a token with a new id and a new mail-address?

**Comment by black-tea** [comment]
Oh yes, thank you! I realized that I had initially used an email address that was already recognized by the Bird API, which explains why I never received the token.
