### ISSUE TITLE
DC Jump Bike Wrapper

### ISSUE THREAD

**Issue by Leschonander** [ubahnverleih/WoBike#40]
I created a basic [wrapper](https://github.com/Leschonander/Jump-Bike-D.C-Python-API-Wrapper) for Jump Bike D.C's open data API. Would you mind adding it and possibly pointing me in a direction on how to upload it to PyPi?

**Comment by ubahnverleih** [comment]
added the link to readme

**Comment by dschep** [comment]
Hey @Leschonander, you might wanna checkout [Python-GBFS](https://github.com/kjschiroo/Python-GBFS) as JUMP's feed (as are many other providers) are in the GBFS format, no need for a custom client :wink:
