### ISSUE TITLE
HTTP 405 Method Not Allowed (Bird API)

### ISSUE THREAD

**Issue by tomasfernandez1212** [ubahnverleih/WoBike#46]
Hey. I'm not really sure what I am doing wrong here. I appreciate any help.

This is pertaining to the bird API. Getting "HTTP 405 Method Not Allowed". This is my python code:

guid=str(uuid.uuid4())
headers={"Device-id": guid, "Platform": "ios","Content-Type": "application/json"}
data = {"email": "<EMAIL-ADDRESS>"}
response = re.get('https://api.bird.co/user/login', data=data,headers = headers)
data = json.loads(response.text)

**Comment by tomasfernandez1212** [comment]
An actual email address would go in the data dictionary of course.

**Comment by cpbergie** [comment]
needs to be a post

**Comment by ubahnverleih** [comment]
Looks like you do a GET request instead a POST request

**Comment by tomasfernandez1212** [comment]
Just figured it out.  Had to change "data=data" to  "json=data":

re.post('https://api.bird.co/user/login', json=data,headers = headers)

**Comment by tomasfernandez1212** [comment]
Thanks a lot!

**Comment by PJPJPJPJPJ** [comment]
I follow this post and use the following code, but I only get the id, didn't get the token. 

`import requests
import simplejson

headers = {"Device-id": "2C97E8DD-0180-40F7-865F-9A8D1886901D", "Platform": "ios", "Content-Type": "application/json"}
login = {"email": "birdapi@gmail.com"}
response = requests.post('https://api.bird.co/user/login', json=login, headers=headers)
data = simplejson.loads(response.text)`

here is my output 
`{u'expires_at': u'2018-09-15T02:40:50.569Z',
 u'id': u'f27983fb-ae19-4d0d-91dd-dc1082bab6f1'}`

Can anyone help me with this? Thank you!

**Comment by ubahnverleih** [comment]
Maybe try another mail address. I remember it only output a token on first use of an mail address.

**Comment by PJPJPJPJPJ** [comment]
Changed it, and it worked! Thank you!
