### ISSUE TITLE
Bird API returning empty results

### ISSUE THREAD

**Issue by camlani** [ubahnverleih/WoBike#47]
Hey, 

Thanks all for starting this project. I am attempting to make some calls based upon location for the Bird API through Postman. My first call to get me my id and token worked just fine, however when requesting based upon latitude and longitude and following the instructions. I receive blank JSON, any tips?
Get Request

https://api.bird.co/bird/nearby?latitude=35.789228&longitude=-78.674706&radius=1000

Headers

```
[{"key":"Authorization","value":"Bird <token> ","description":""},
{"key":"Device-id","value":"ee2cc530-1382-4e6f-9a97-dfe4859d145b","description":""},
{"key":"App-Version","value":"3.0.5","description":""},
{"key":"Location","value":"{\"latitude\":35.789228,\"longitude\":-78.674706}","description":""}]
```

Result
```
{
    "birds": [],
    "clusters": [],
    "areas": []
}
```

Thanks for your help!

**Comment by PierrickP** [comment]
If your http status code is 200, your result is right.
There are no Bird around this location.
