### ISSUE TITLE
R submit post request doesn't return id or token

### ISSUE THREAD

**Issue by PJPJPJPJPJ** [ubahnverleih/WoBike#50]
Hi! I am not very familiar with Python so I use R to try submit the POST request. Here is the code that I used.

``` r
library(httr)

res <- POST("https://api.bird.co/user/login", body = "birdsapi@gmail.com", add_headers("Device-id"="2C97E8DD-0180-40F7-865F-9A8D1886901D",
                                                                        "Platform" = "ios",
                                                                        "Content-type" = "application/json"))

```

Created on 2018-09-14 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

It return me with this object, but I can't find id or token in it.
<img width="776" alt="screen shot 2018-09-14 at 4 37 30 pm" src="https://user-images.githubusercontent.com/24664414/45574022-81cc5280-b83c-11e8-8e67-9fa3c60fb877.png">
<img width="781" alt="screen shot 2018-09-14 at 4 37 59 pm" src="https://user-images.githubusercontent.com/24664414/45574032-91e43200-b83c-11e8-8fed-1faddcb115c9.png">

Can anybody tell me where I am doing it wrong? Thanks!

**Comment by PierrickP** [comment]
status code is 400, so something is wrong (your body should be a JSON `{"email": "<EMAIL-ADDRESS>"}`).
You can use curl or postman/insomnia to test before
