### ISSUE TITLE
Gobee.bike in Torino Italy

### ISSUE THREAD

**Issue by MartinoMensio** [ubahnverleih/WoBike#6]
Today 2 November 2017 a new bike sharing system started operating in Torino, Italy. You can find sime info in italian here: http://torino.repubblica.it/cronaca/2017/10/31/news/sbarca_a_torino_il_bike_floating_biciclette_a_flusso_libero_da_usare_e_lasciare_dove_si_svuole-179841919/
The URL seems to be the same as Hong Kong, but with locations in Torino. Example of request: http://aws.gobee.bike/GobeeBike/bikes/near_bikes?accuracy=20&lat=45.070049&lng=7.68645

**Comment by ubahnverleih** [comment]
Thanks, I added Italy as country on gobee
