### ISSUE TITLE
Has Lime changed their scooter list API URL?

### ISSUE THREAD

**Issue by MichaelSimek** [ubahnverleih/WoBike#66]
I can call the token request and key request and it does work but when I call the https://web-production.lime.bike/api/rider/v1/views/main one with all the params it returns 404 it did work 4 days ago. Have they changed the URL?

**Comment by PierrickP** [comment]
https://github.com/ubahnverleih/WoBike/issues/9#issuecomment-451670072

**Comment by MichaelSimek** [comment]
Thanks, that works.

**Comment by Mradmedamine** [comment]
Hello Pierrick,
where is the juicer api ? there is only the rider.
How could you intercept the URLs. I'm trying to do this with my phone and I receive an SSL error with burp . 

 _The client failed to negotiate an SSL connection to web-production.lime.bike:443: Remote host closed connection during handshake_

Does lime app have SSL pinning ?
Please help !!
