### ISSUE TITLE
[Limebike] request URL does not work with co-ordinates changed.

### ISSUE THREAD

**Issue by AhmedSamara** [ubahnverleih/WoBike#7]
`https://web-production.lime.bike/api/public/v1/views/bikes?map_center_latitude=37.7604&map_center_longitude=-122.4398&user_latitude=37.7604&user_longitude=-122.4398`

Whenever I try to swap out the latitude and longitude I just get an empty list:

`https://web-production.lime.bike/api/public/v1/views/bikes?map_center_latitude=66.117844&map_center_longitude=-80.507813&user_latitude=37.7604&user_longitude=-80.507813`

`{"data":{"id":"views::publicbikesview","type":"public_bikes_view","attributes":{"nearby_locked_bikes":[],"default_bike_icon":{"id":"1","type":"icons","attributes":{"url":"https://d22d5yy1i19g9i.cloudfront.net/icons/default_pin.png?fingerprint=821a3e688143dfcebac869d8f9e4b97b","description":"","description_icon_url":null,"description_link_url":null}},"cluster_icon":{"id":"2","type":"icons","attributes":{"url":"https://d22d5yy1i19g9i.cloudfront.net/icons/default_cluster.png?fingerprint=23bbfa670fea1998a61b91512c1a15d9","description":"","description_icon_url":null,"description_link_url":null}}}},"meta":{"min_ios_version":"1.4.1","min_android_code":19,"flags":"IOS_VERSION_V1.0,ANDROID_VERSION_V1.0","groups":[]}}`

**Comment by ubahnverleih** [comment]
hm, the map center location is somewhere in the sea and the user location is somewhere on a mountain – maybe there are no bikes near this location. I guess the bikes needs to be in a specific distance to the user location

**Comment by AhmedSamara** [comment]
AH, I should mention I obfuscated lat and lon because I didn't want to just post my location online, but got the same result with my actual location (which has bikes nearby).

However on trying again, I just realized I have to trim the decimal places and it works now.
