### ISSUE TITLE
Not Getting Token From Bird

### ISSUE THREAD

**Issue by ctriley** [ubahnverleih/WoBike#76]
`URL = "https://api.bird.co/user/login"`
 `data = {"email": "bob@gmail.com"}`
 `headers = {"Device-id": "4db3bd94-308c-493b-a6fa-1e8398a376ab", "Platform": "ios", "Content-type": "application/json"}`
 `r = requests.post(url = URL, headers=headers, json=data)`
 `response = json.loads(r.text)`
 `print(r.text)`

Results in the following:
{"id":"b037424f-05d7-495d-83c3-980c7ec7dd8a","expires_at":"2019-01-24T22:55:24.804Z"}

There is no token given.

**Comment by ctriley** [comment]
If anyone else is having this problem -- the email address matters. Use one that hasn't been used before and you'll get a token.

**Comment by lowbrows** [comment]
Hey ctriley, here's my function to get the initial token:

def get_token():
    email= uuid2[0:4]+"@yahoo.com"
    url="https://api.bird.co/user/login"
    payload = {'email': email}
    headers = {'Device-id': uuid2, 'Platform':'ios', 'Content-type': 'application/json'}
    response = requests.post(url, data=json.dumps(payload), headers=headers)
    login= json.loads(response.text)
    print login
    token=login["token"]
    return token
--------------------------------------
it returns---
{u'token': u'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBVVRIIiwidXNlcl9pZCI6IjNhMzhmNWU1LWFhNjEtNDJkMi04Y2YyLTY5NTViNWQ4NzcwMSIsImRldmljZV9pZCI6IjA1ZjIyMzc3LWYyMDMtNDY0Ni1hMjdmLTEzMTA3MTNiY2FlNyIsImV4cCI6MTU3OTkwOTQzOH0.AX_M-1IHtqKQV4h5eCRkNTTIWD942O_WKjg7Iw4J8xY', u'id': u'4c8bf6c5-5bee-47af-84bf-80e417c9ff69'}
  
The token needs to get stored and then passed again to another function.  I think what you are getting is the token renewal.  If you want my data collection script I can post it.  

Best
