### ISSUE TITLE
Request: Add link to VOI API resource

### ISSUE THREAD

**Issue by William04A** [ubahnverleih/WoBike#77]
Hi! I recently submitted a PR with the VOI scooter API. I had no idea that this awesome and detailed blog post with some cool examples existed:
[https://medium.com/@h_martos/remote-live-tracking-of-voi-scooters-351689ba3bb9](https://medium.com/@h_martos/remote-live-tracking-of-voi-scooters-351689ba3bb9)

I didn´t want to make another PR just to add a single sentence, but I thought that someone with write-access to the repository could add a reference to the link.

I can always make a new PR if needed ;)

**Comment by ubahnverleih** [comment]
Added link, thank you :)

**Comment by Mradmedamine** [comment]
Hey ! please consider my new issue https://github.com/ubahnverleih/WoBike/issues/75
it has been a while waiting. I urgently need some help to discover the juicer api.
Thanks in advance !!!
