### ISSUE TITLE
Add scoot

### ISSUE THREAD

**Issue by robbi5** [ubahnverleih/WoBike#86]
Site: https://scoot.co
Android: https://play.google.com/store/apps/details?id=co.scoot.scootapp
iOS: https://itunes.apple.com/us/app/scoot-networks/id1361793328

**Comment by robbi5** [comment]
App Configuration and Service Area bounds:
https://app.scoot.co/api/v1/region_manifest 

Locations of Parking Garages (for their bigger electric scooters):
https://app.scoot.co/api/v3/locations.json

Positions of bigger Scooters and kick scooters:
https://app.scoot.co/api/v1/scooters.json

The API describes the kickscooters as _Turbo Mini Telepod Kick Scooter_. So it seems like Scoot is using hardware from https://www.telepod.co

**Comment by davidwim** [comment]
Aquired by Bird. The API's listed above have been shut down.
