### ISSUE TITLE
Hive Command cline prompt

### ISSUE THREAD

**Issue by lspacewang** [ubahnverleih/WoBike#90]
After the command line is connected to hive, the function can be intelligently reminded. For example, if you input se, it will automatically associate select, input the first few letters of the table name, and you can associate the table name,how to do ? Thanks.

**Comment by lspacewang** [comment]
How to do it ?

**Comment by robbi5** [comment]
It looks like you are talking about _Apache Hive_. This repository (and issues) don't have anything in common with Apache Hive - here we talk about Bikesharing Providers and their APIs. Please use StackOverflow or the respective hive community for your question. Thanks.

**Comment by lspacewang** [comment]
> It looks like you are talking about _Apache Hive_. This repository (and issues) don't have anything in common with Apache Hive - here we talk about Bikesharing Providers and their APIs. Please use StackOverflow or the respective hive community for your question. Thanks.

Sorry about that.
